package com.example.model

object CODMachineRepository {
    fun getMachines(): List<CODMachine> {
        return listOf(
            CODMachine.create("KeyBS Merchant", "Bin Omran Branch-KeyBS Merchant", "10000135", "https://maps.app.goo.gl/r7JNNza8Vt18HLtJ9"),
            CODMachine.create("Fresh Way Supermarket", "Al Rayyan Branch-Fresh Way Supermarket", "10000140", "https://maps.app.goo.gl/kA3MRiBFLtp4pq3T6"),
            CODMachine.create("Zadak Hypermarket", "Sanniya Branch-Zadak Hypermarket", "10000141", "https://goo.gl/maps/bn8WJx1AxRbPD8Ar6"),
            CODMachine.create("LU Grocery", "Sanniya Branch-LU Grocery", "10000142", "https://goo.gl/maps/8fut43DTvXjzqBaE9"),
            CODMachine.create("Khayrat Al Doha Hypermarket", "Mamoura Banch-Khayrat Al Doha", "10000144", "https://goo.gl/maps/9scqJvk5i3BG6CuY6"),
            CODMachine.create("Point Eight Supermarket", "Al Wukair Branch-Point Eight Supermarket", "10000149", "https://maps.app.goo.gl/4CorJYkmoEjpqR9c9"),
            CODMachine.create("Prime Touch Delivery", "Sanniya Branch-Prime Touch Delivery", "10000153", "https://waze.com/ul/hthkx5p855"),
            CODMachine.create("Cassava Mini Mart", "Al Saad Branch-Cassava Mini Mart", "10000155", "https://goo.gl/maps/wFZ4UWUJMMyKpNZv5"),
            CODMachine.create("Al Abid Supermarket", "Al Khor Branch-Al Abid Supermarket", "10000156", "https://maps.app.goo.gl/LuxwVrj1dpLwANZL8"),
            CODMachine.create("Dafna Prime Mart", "Dafna Branch- Dafna Prime Mart", "10000159", "https://maps.app.goo.gl/r9vtQPJSNLFNX96p8"),
            CODMachine.create("Madeena Hypermarket", "Wakra Branch- Madeena Hypermarket", "10000160", "https://goo.gl/maps/v5aaGiHGVVuCjuL38"),
            CODMachine.create("Al Shariyas Food Center", "Al Saad Branch-Al Shariyas Food Center", "10000164", "https://goo.gl/maps/B9ysVozHbCorZuhBA"),
            CODMachine.create("Wadi Al Dahab", "Freej Abdul Azeez Branch-Wadi Al Dahab", "10000165", "https://goo.gl/maps/FzvMpcUvYTXArkQF7"),
            CODMachine.create("Muraikh Food Complex", "Muaither Branch-Muraikh Food Complex", "10000166", "https://goo.gl/maps/QxQBknV6eHHHi8K1A"),
            CODMachine.create("Mobile Point", "Wakra Branch-Mobile Point", "10000167", "https://goo.gl/maps/tX3tzXWTEoZk6afj7"),
            CODMachine.create("Al Hamed Grocery", "Najma Branch-Al Hamed Grocery", "10000168", "https://goo.gl/maps/cTPwzQJCkwp54Qpq5"),
            CODMachine.create("Metro Mart", "Souq Al Jaber Branch-Metro Mart", "10000169", "https://maps.app.goo.gl/Mt5AYkuGCsXcQigV8"),
            CODMachine.create("Wusail Shopping Centre", "Um Salal Ali Branch-Wusail Shopping Centre", "10000171", "https://maps.app.goo.gl/AF31MsdtqxjwUJDm6"),
            CODMachine.create("Sanniya Food City Market", "Sanniya Branch-Sanniya Food City Market", "10000172", "https://maps.app.goo.gl/mFy3X27RC1AkFQou5"),
            CODMachine.create("Al Hadoud Supermarket", "Al Khor Branch-Al Hadoud Supermarket", "10000175", "https://goo.gl/maps/YkQroFZcndARTu7f9"),
            CODMachine.create("Al Danube Food Stuff", "Sanniya Branch- Al Danube Food Stuff", "10000180", "https://maps.app.goo.gl/mMGvBRX9CDP9UomZ7"),
            CODMachine.create("Rawiya Supermarket", "Al Kharaitiyat Branch Rawiya Supermarket", "10000181", "https://goo.gl/maps/7gduuobToyPgCgQZ6"),
            CODMachine.create("Info Madeena Mobile", "Madeena Khalifa Branch-Info Madeena Mobile", "10000182", "https://goo.gl/maps/foXf53BdmhWYiH3i7"),
            CODMachine.create("Go Do Delivery-1", "Sanniya Branch-Go Do Delivery-1", "10000183", "https://maps.app.goo.gl/dNTckpE2uWWW9bXr7"),
            CODMachine.create("Al Ikhlas Supermarket", "Al Rayyan Branch-Al Ikhlas Supermarket", "10000185", "https://maps.app.goo.gl/W3LFxmbUSDfDzoQu8"),
            CODMachine.create("Mishal Supermarket", "Al Saad Branch-Mishal Supermarket", "10000187", "https://maps.app.goo.gl/fxJdJ1BDHqXDNf8t5"),
            CODMachine.create("Mr.Delivery", "Sanniya Branch-Mr.Delivery", "10000193", "https://goo.gl/maps/PVzhkiSaubiMNdC78"),
            CODMachine.create("Falcon Big Mart", "Bin Omran Branch-Falcon Big Mart", "10000194", "https://maps.app.goo.gl/JTuiEmcdZK2ybdcu7"),
            CODMachine.create("Blue Diamond Supermarket", "Muglina Branch-Blue Diamond Supermarket", "10000195", "https://maps.app.goo.gl/oDy9iPSK8yiMLWdi8"),
            CODMachine.create("Jaal Phone", "Al Khor Branch-Jaal Phone", "10000197", "https://goo.gl/maps/J3QQYuVU3aKMGXwYA"),
            CODMachine.create("Cosmo Supermarket", "Ain Khalid Branch-Cosmo Supermarket", "10000198", "https://goo.gl/maps/KMi1o6PZDudHgjvPA"),
            CODMachine.create("Fresh Choice Supermarket", "Al Aziziya Branch-Fresh Choice Supermarket", "10000199", "https://maps.app.goo.gl/Y9bXSRRRQRQNPvh2A"),
            CODMachine.create("Arbash Mobile", "Wakra Branch-Arbash Mobile", "10000200", "https://goo.gl/maps/tFncaesk1RnQ3zgX7"),
            CODMachine.create("Green Fresh Supermarket", "Sanniya Branch-Green Fresh Supermarket", "10000201", "https://maps.app.goo.gl/zwVKVTAPf5XsYANT7"),
            CODMachine.create("Marzam Supermarket", "Sanniya Branch-Marzam Supermarket", "10000202", "https://maps.app.goo.gl/QhZ6fTvYJAHWceibA"),
            CODMachine.create("Grandex Supermarket", "Al Azizia Branch-Grandex Supermarket", "10000204", "https://goo.gl/maps/NhcbxMKV2danYDQe9"),
            CODMachine.create("Int.Tel.Centre", "Wakra Branch-Int.Tel.Centre", "10000207", "https://goo.gl/maps/N9u51HqmyjH2"),
            CODMachine.create("Malabar Supermarket", "Sanniya Branch-Malabar Supermarket", "10000208", "https://goo.gl/maps/ZK3gF15D6yDFncab6"),
            CODMachine.create("Bathool Supermarket", "Lusail Branch-Bathool Supermarket", "10000211", "https://maps.app.goo.gl/PubPTcHtkb8EBeoN7"),
            CODMachine.create("Swift Delivery-1", "Al Wukair Branch-Ezdan 29", "10000212", "https://goo.gl/maps/xBcoQB8XW9nnuK548"),
            CODMachine.create("Al Fajer Shopping Center", "Najma Branch-Al Fajer Shopping Center", "10000213", "https://goo.gl/maps/bFq46uZt9L98Ge539"),
            CODMachine.create("Swift Delivery-4", "Al Wukair Branch- swift Ezdan 29", "10000214", "https://goo.gl/maps/xBcoQB8XW9nnuK548"),
            CODMachine.create("Seven Mart Hypermarket", "Fereej Abdul Azeez Branch-Seven Mart Hypermarket", "10000215", "https://maps.app.goo.gl/3Q3LLwMtyz6iatFj7"),
            CODMachine.create("Danube Supermarket", "Sanniya Branch-Danube Supermarket", "10000217", "https://goo.gl/maps/q88JrGRgNJBP6Dfx7"),
            CODMachine.create("Al Hebah Subermarket", "Sanniya Branch-St16-Al Hebah Subermarket", "10000218", "https://maps.app.goo.gl/TupouoX4VSZVQziR9"),
            CODMachine.create("Swift Delivery-2", "Al Wukair Branch- Ezdan 32", "10000219", "https://goo.gl/maps/xBcoQB8XW9nnuK548"),
            CODMachine.create("Sanniya Food City Market-3", "Sanniya Branch-Sanniya Food City Market-3", "10000220", "https://waze.com/ul/hthkx4ytyb"),
            CODMachine.create("Masters Supermarket", "Simaisma Branch-Masters Supermarket", "10000221", "https://maps.app.goo.gl/AtRFG6cN8p9szFpA6"),
            CODMachine.create("Deshi Taza Hypermarket", "Al Aziziya Branch-Deshi Taza Hypermarket", "10000222", "https://maps.app.goo.gl/sp3MGcDxGpZhH8ss5"),
            CODMachine.create("Al Shariyas Food Center Azizyza", "Al Aziziya Branch-Al Shariyas Food Center Azizyza", "10000223", "https://maps.app.goo.gl/gegeNBnxumrUfkoE9"),
            CODMachine.create("Clear Zone Supermarket", "Al Kheesa Branch- Clear Zone Supermarket", "10000224", "https://goo.gl/maps/CFtegk5cJVDGvFes9"),
            CODMachine.create("Shop Well Supermarket", "Sanniya Branch-Shop Well Supermarket", "10000225", "https://maps.app.goo.gl/kHpWgLM7jWenpDde6"),
            CODMachine.create("Delivex Delivery", "Saniiya Branch-Delivex Delivery", "10000226", "https://waze.com/ul/hthkx61hw3"),
            CODMachine.create("Garden Fresh Supermarket", "Muntazah Branch- Garden Fresh Supermarket", "10000227", "https://goo.gl/maps/MGwEpzhbq7aN8YAC9"),
            CODMachine.create("Rosa Supermarket", "Al Saad Branch-Rosa Supermarket", "10000228", "https://maps.app.goo.gl/CzrCSzo5ap1eVBRj7"),
            CODMachine.create("Salik Delivery", "Saniiya Branch-Salik  Delivery", "10000229", "https://maps.app.goo.gl/AgAceFcjtYD8gFQ76"),
            CODMachine.create("Swift Delivery-3", "Al Wukair Branch-Swift Ezdan 38", "10000230", "https://goo.gl/maps/g2LAWC6uXXSTYUwA7"),
            CODMachine.create("Fast Grocery 2", "Mansoura Branch-Fast Grocery 2", "10000231", "https://maps.app.goo.gl/Wgae38zJ77ojRJ1D8"),
            CODMachine.create("Maherjeh Grocery", "Thumama Branch- Maherjeh Grocery", "10000232", "https://maps.app.goo.gl/6fPDpK4GJRNZ17Z36"),
            CODMachine.create("Bongo Bazar Supermarket", "Khartiyat Branch-Bongo Bazar Supermarket", "10000233", "https://maps.app.goo.gl/v8AN8NuUMSmTB4iD7"),
            CODMachine.create("New Kenz Supermarket", "Al Aziziya Branch-New Kenz Supermarket", "10000234", "https://maps.app.goo.gl/rUAcMytKeKX5hhin6"),
            CODMachine.create("Al Mashoor Supermarket", "Al Wukair Branch-Al Mashoor Supermarket", "10000235", "https://maps.app.goo.gl/pDGAXAh7upRHHYf1A"),
            CODMachine.create("Tawa Trading & Services", "Old Airport Road Branch-Tawa Trading & Services", "10000236", "https://goo.gl/maps/iMAfKnHDdFH49gaD7"),
            CODMachine.create("Food Corner Supermarket", "Abu Hamour Branch-Food Corner Supermarket", "10000237", "https://goo.gl/maps/Hs7Um5263eiLd8tB9"),
            CODMachine.create("WIFI Grocery", "Sanniya Branch-WIFI Grocery", "10000238", "https://maps.app.goo.gl/CfKUQEpznHpcne3p8"),
            CODMachine.create("Friendly Mart", "Najma Branch-Friendly Mart", "10000240", "https://goo.gl/maps/eUioBS87vagfREFz9"),
            CODMachine.create("Al Kuwari Food Stuff", "Madina Khalifa Branch-Al Kuwari Food Stuff", "10000241", "https://goo.gl/maps/Hr7eySeqtrMiC6w96"),
            CODMachine.create("Al Nosour Delivery", "Sanniya Branch-Al Nosour Delivery", "10000242", "https://maps.app.goo.gl/6WTsrMBhF4vCUXNj"),
            CODMachine.create("Carry Food Minimart", "Bin Mahmood Branch-Carry Food Minimart", "10000243", "https://maps.app.goo.gl/H3erDHza7FfsxL7w9"),
            CODMachine.create("Cmax Mobiles & Watches", "Salwa Road Branch- Cmax Mobiles & Watches", "10000244", "https://maps.app.goo.gl/2R86BrmV5qZEhdM37"),
            CODMachine.create("Monir Supermarket", "Sanniya Branch-Monir Supermarket", "10000245", "https://maps.app.goo.gl/RzkgTDHtVgHnghpK8"),
            CODMachine.create("Al Markhiya Mobiles", "Al Markhiya Branch-Al Markhiya Mobiles", "10000246", "https://goo.gl/maps/dfT4VdhdqffNwGBSA"),
            CODMachine.create("Sanniya Food City Market-2", "Sanniya Branch-Sanniya Food City Market-2", "10000247", "https://maps.app.goo.gl/No4fejHDL1uHXNdW9"),
            CODMachine.create("Siniyari Grocery", "Sanniya Branch-Siniyari Grocery", "10000248", "https://maps.app.goo.gl/G9xLura2Hb66zhLd6"),
            CODMachine.create("Shahbiyah Supermarket", "Al Waab Branch- Shahbiyah Supermarket", "10000249", "https://goo.gl/maps/NWurvSQbTXkABumb9"),
            CODMachine.create("Urban Food Market-2", "New Salata Branch-Urban Food Market-2", "10000250", "https://maps.app.goo.gl/VVwHE7B8ivKViSGg6"),
            CODMachine.create("Food City Market", "Al Saad Branch-Food City Market", "10000251", "https://maps.app.goo.gl/no4JPtGu9HDgzRTRA"),
            CODMachine.create("Selection Mart Supermarket", "Hilal Branch-Selection Mart Supermarket", "10000252", "https://goo.gl/maps/uGq4rB1Ni4Mfkuq86"),
            CODMachine.create("Al Koot Supermarket", "Al Kheesa Branch-Al Koot Supermarket", "10000253", "https://goo.gl/maps/whqnbeKRxeBVVp4u9"),
            CODMachine.create("Shimla Grocery", "Sanniya Branch-Shimla Grocery", "10000254", "https://goo.gl/maps/JJD6wZgKkyYh96P2A"),
            CODMachine.create("Samyog Trading & Services", "Souq Al Jaber Branch-Samyog Tading & Services", "10000255", "https://maps.app.goo.gl/9RmPXoU6jLDp1z736"),
            CODMachine.create("Door Step Supermarket", "Fereej Abdul Azeez Branch-Door Step Supermarket", "10000256", "https://maps.app.goo.gl/DE4QJRZDTY9nD68F6"),
            CODMachine.create("Al Kausar Supermarket", "Al Gharaffa Branch-Al Kausar Supermarket", "10000257", "https://maps.app.goo.gl/igXSnnE71gPJqw6K9"),
            CODMachine.create("Afia Mart", "Al Rayyan Branch- Afia Mart", "10000258", "https://maps.app.goo.gl/Wu6hxybSzwhTpH4f9"),
            CODMachine.create("Beep Delivery", "Sanniya Branch-Beep Delivery", "10000259", "https://maps.app.goo.gl/xZ7hTFCV7VjqbXo27"),
            CODMachine.create("Smart Shopping center", "Muntazah Branch-Smart Shopping Center", "10000260", "https://goo.gl/maps/uT3zNS2nfimqmDGS6"),
            CODMachine.create("Perfect Mobiles", "Bin Omran Branch-Perfect Mobile", "10000261", "https://maps.app.goo.gl/6tw83CtNUnV3K6BcA"),
            CODMachine.create("SRS Restaurant", "Al Rayyan Branch-SRS Restaurant", "10000262", "https://goo.gl/maps/psA7stN5AamQQhXf7"),
            CODMachine.create("Go Do Delivery-3", "Sanniya Branch-Go Do Delivery-3", "10000263", "https://goo.gl/maps/ogBnqiangNzoMSo18"),
            CODMachine.create("Noor Al Wakra Food Center", "Wakra Branch-Noor Al Wakra Food Center", "10000264", "https://goo.gl/maps/ZAPNT2is4JTGmkbBA"),
            CODMachine.create("Al Malki Trade Center Supermarket", "Al Khor Branch-Al Malki Trade Center Supermarket", "10000265", "https://maps.app.goo.gl/ZZoSHMSCYdtCii5q6"),
            CODMachine.create("Fast Grocery", "Mansoura Branch-Fast Grocery", "10000266", "https://goo.gl/maps/La5aDJm1pBP8UUmF8"),
            CODMachine.create("Noorul Arab cafeteria", "Sanniya Branch-Noorul Arab cafeteria", "10000267", "https://goo.gl/maps/GTJE4TTmpzYWqFQX7"),
            CODMachine.create("Shams Al Madeena Supermarket", "Sanniya Branch-Shams Al Madeena Supermarket", "10000268", "https://maps.app.goo.gl/HP9LS78pLBGV5xiy8"),
            CODMachine.create("Iqra Supermarket", "Bin Omran Branch-Iqra Supermarket", "10000269", "https://goo.gl/maps/v2baFkkEKpLkXtMQ7"),
            CODMachine.create("Al Habari Food Stuff", "Al Khor Branch-Al Habari Food Stuff", "10000270", "https://goo.gl/maps/NhtzxMax1z5msh2QA"),
            CODMachine.create("Garden Fresh Supermarket-2", "Muglina Branch-Garden Fresh Supermarket-2", "10000271", "https://goo.gl/maps/t7ZcyxDAScun4DGs9"),
            CODMachine.create("Onesa Supermarket", "Sanniya Branch-Onesa Supemarket", "10000272", "https://goo.gl/maps/cyPo1EDoSDNV6NhTA"),
            CODMachine.create("Al Hammadi Supermarket", "Sanniya Branch-Al Hammadi Supermarket", "10000273", "https://maps.app.goo.gl/w3swmXvPuFZ9B3VdA"),
            CODMachine.create("New Madeena Hypermarket", "Doha Jadeed Branch-New Madeena Hypermarket", "10000274", "https://goo.gl/maps/vWzhzuSAQNRGypGq6"),
            CODMachine.create("Go Do Delivery-4", "Sanniya Branch-Go Do Delivery-4", "10000275", "https://maps.app.goo.gl/dNTckpE2uWWW9bXr7"),
            CODMachine.create("Jaseela Supermarket", "Umm Garn Branch-Jaseela Supermarket", "10000277", "https://goo.gl/maps/r2JSTASj193A4jjJ7"),
            CODMachine.create("Dolphin Grocery", "Sanniya Branch-Dolphin Grocery", "10000278", "https://goo.gl/maps/rcxvqvBmuhPSzV5v9"),
            CODMachine.create("Galaxy Food Centre", "Muntazah Branch-Galaxy Food Centre", "10000279", "https://goo.gl/maps/zFhz9N64URHswN9S6"),
            CODMachine.create("LULU AL BIDA GROCERY", "Al Kheesa Branch-LULU AL BIDA GROCERY", "10000280", "https://goo.gl/maps/VifXsWPNb8dZ5vma9"),
            CODMachine.create("Road Track Trading", "Muglina Branch-Road Track Trading", "10000281", "https://goo.gl/maps/kk86iDWPNZUR4EE38"),
            CODMachine.create("Road Track Trading-2", "Fereej Abdul Azeez Branch-Road Track Trading-2", "10000282", "https://maps.app.goo.gl/E38FDmGb8duCD1h16"),
            CODMachine.create("Able Mart Hypermarket", "sanniya Branch-Able Mart Hypermarket", "10000283", "https://maps.app.goo.gl/Gzpz4k2xtewzBCaRA"),
            CODMachine.create("Danube Food Center", "Sanniya Branch-Danube Food Centre", "10000284", "https://goo.gl/maps/uvBZTFQ2Y4pDCDi5A"),
            CODMachine.create("Al Fajer Shopping Center-2", "Sanniya Branch- Al Fajer Shopping Center-2", "10000285", "https://goo.gl/maps/bn8WJx1AxRbPD8Ar6"),
            CODMachine.create("Star Max Grocery", "Sanniya Branch- Star Max Grocery", "10000286", "https://goo.gl/maps/JnhNYX1G73qfkdsDA"),
            CODMachine.create("Paradise Grocery", "Sanniya Branch-Paradise Grocery", "10000287", "https://goo.gl/maps/wMYrHHEGEm4Hq3jJ8"),
            CODMachine.create("Oruma Grocery", "Sanniya Branch-Oruma Grocery", "10000288", "https://goo.gl/maps/BsDKsMVZtwT7ANar7"),
            CODMachine.create("Better Buys Trading", "Muntazah Branch-Better Buys Trading", "10000289", "https://goo.gl/maps/tCJrJ8tvCnRuPSVK7"),
            CODMachine.create("PRIME MART-2", "Salwa Road-Prime Mart-2", "10000290", "https://goo.gl/maps/guM1QFjiqDJigujb8"),
            CODMachine.create("Insaaf Supermarket", "Al Aziziya Branch-Insaaf Supermarket", "10000291", "https://maps.app.goo.gl/1bYnoCp28PrCmzxQA"),
            CODMachine.create("Go Do Delivery-2", "Sanniya Branch-Go Do Delivery-2", "10000292", "https://maps.app.goo.gl/8SETSMsGNfxhxyoTA"),
            CODMachine.create("Dolphin Grocery-2", "Sanniya-37 Branch-Dolphin Grocery-2", "10000293", "https://goo.gl/maps/bgNuBq9AwGJ8AuFN9"),
            CODMachine.create("Al Kaabi Grocery", "Madina Khalifa Branch-Al Kaabi Grocery", "10000294", "https://goo.gl/maps/qru7QGZq41SsYjG99"),
            CODMachine.create("Skyline Supermarket", "Lukta Branch-Skyline Supermarket", "10000295", "https://goo.gl/maps/3z5veTkKu9541kF4A"),
            CODMachine.create("Food Market", "Sanniya Branch-Food Market", "10000296", "https://goo.gl/maps/bWswKTAvwDrHm7FeA"),
            CODMachine.create("Grand Bazar Supermarket", "Doha Jadeed Branch-Grand Bazar Supermarket", "10000297", "https://goo.gl/maps/sERGqyrzLCBoz6zK7"),
            CODMachine.create("Prime Mart", "Midmac Signal Branch-Prime Mart", "10000298", "https://goo.gl/maps/qDn8FgctmWu3NSNe6"),
            CODMachine.create("Kfone Trading", "Muntaza Branch-Kfone Trading", "10000303", "https://goo.gl/maps/KPjta6YbiVWUkzMSA"),
            CODMachine.create("Abdulla Al Jaber Grocery", "Sanniya Branch-Abdulla Al Jaber Grocery", "10000309", "https://goo.gl/maps/NzNAuxhsHLZ9BD4GA"),
            CODMachine.create("Global Smart Trading", "Muaither Branch-Global Smart Trading", "10000417", "https://maps.app.goo.gl/qkRVPC9eCsbXFv9d7"),
            CODMachine.create("HFM Supermarket", "Ain Khalid Branch-HFM Supermarket", "10000418", "https://maps.app.goo.gl/Ey7j7yxWDf19UYbBA"),
            CODMachine.create("Nana Food Mart", "UmSalal Ali Branch- Nana Food Mart", "10000419", "https://maps.app.goo.gl/JyajYxxscgdsiHRj9")
        )
    }
}
